# Generated by Django 3.2.16 on 2023-01-25 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('api_token', models.CharField(help_text="For help on how to generate your API TOKEN click <a href='https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-manage-API-access-tokens-as-an-instructor/ta-p/1177' target='_blank'>here</a>.", max_length=128)),
                ('subject', models.CharField(blank=True, default='', help_text='For example: LIFE, MATH, ARCH, etc ...', max_length=4, null=True)),
                ('course_codes', models.TextField(blank=True, default=None, verbose_name='Additional Courses')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('repeat', models.CharField(choices=[('one-off task', 'One-off Task'), ('every day', 'Every Day'), ('every 7 days', 'Every Week')], default='one-off task', max_length=20)),
                ('additional_recipients', models.TextField(blank=True, default='', null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lens.institute')),
                ('periodic_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lens.term')),
            ],
        ),
    ]
